[build]
  base = "fenago21"
  command = "npm ci --legacy-peer-deps && npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20.11.1"

[[plugins]]
  package = "@netlify/plugin-nextjs"